In [6]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.stat import Correlation

data = [(Vectors.sparse(4, [(0, 1.0), (3, -2.0)]),),
        (Vectors.dense([4.0, 5.0, 0.0, 3.0]),),
        (Vectors.dense([6.0, 7.0, 0.0, 8.0]),),
        (Vectors.sparse(4, [(0, 9.0), (3, 1.0)]),)]
df = spark.createDataFrame(data, ["features"])

r1 = Correlation.corr(df, "features").head()
print("Pearson correlation matrix:\n" + str(r1[0]))

r2 = Correlation.corr(df, "features", "spearman").head()
print("Spearman correlation matrix:\n" + str(r2[0]))

NameError: name 'spark' is not defined

In [31]:
from pyspark.sql import SparkSession

logFile = "/Volumes/BOOTSTRAP/spark-3.1.2-bin-hadoop3.2/README.md"  # Should be some file on your system
spark = SparkSession.builder.appName("SimpleApp").getOrCreate()
logData = spark.read.text(logFile).cache()

numAs = logData.filter(logData.value.contains('a')).count()
numBs = logData.filter(logData.value.contains('b')).count()

print("Lines with a: %i, lines with b: %i" % (numAs, numBs))

spark.stop()


Could not find valid SPARK_HOME while searching ['/Users/a10.11.5/人工智能demos', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark/spark-distribution', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark/spark-distribution', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark', '/Users/a10.11.5/anaconda3/lib/python3.7']


SystemExit: -1

/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3275: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [8]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

Could not find valid SPARK_HOME while searching ['/Users/a10.11.5/人工智能demos', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark/spark-distribution', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark/spark-distribution', '/Users/a10.11.5/anaconda3/lib/python3.7/site-packages/pyspark', '/Users/a10.11.5/anaconda3/lib/python3.7']


SystemExit: -1

In [12]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.constant([1.0,2.0],name='a')
b = tf.constant([2.0,3.0],name='b')

result = a + b

sess = tf.compat.v1.Session()
sess.run(result)

array([3., 5.], dtype=float32)

In [22]:
def make_variables(k, initializer):
    return (tf.Variable(initializer(shape=[k], dtype=tf.float32)),
          tf.Variable(initializer(shape=[k, k], dtype=tf.float32)))

In [29]:
g1 = tf.Graph()
with g1.as_default():
    v = make_variables(1, tf.zeros_initializer())
g2 = tf.Graph()
with g2.as_default():
    v = make_variables(1, tf.ones_initializer())    

with tf.compat.v1.Session(graph=g1) as sess:
    tf.compat.v1.global_variables_initializer()
    with tf.compat.v1.variable_scope("",reuse=True):
        print(sess.run(tf.compat.v1.get_variable("v")))

with tf.compat.v1.Session(graph=g2) as sess:
    tf.compat.v1.global_variables_initializer()
    with tf.compat.v1.variable_scope("",reuse=True):
        print(sess.run(tf.compat.v1.get_variable("v")))        

ValueError: Variable v does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

In [33]:
v1, v2 = make_variables(3, tf.zeros_initializer())

In [32]:
import torch

In [34]:
torch.IntTensor(2,3)

torch.FloatTensor(2,3)

torch.empty(2,3)


tensor([[ 0.0000e+00,  0.0000e+00, -8.1935e-04],
        [ 2.8615e-42, -4.4189e-02,  4.5799e-41]])

In [35]:
import numpy as np

arr = np.array([1,2,3,4,5])

a1 = torch.tensor(arr)
a2 = torch.as_tensor(arr)
a3 = torch.from_numpy(arr)

In [36]:
a1

tensor([1, 2, 3, 4, 5])

In [37]:
a2

tensor([1, 2, 3, 4, 5])

In [38]:
a3

tensor([1, 2, 3, 4, 5])

In [39]:
arr[0] = 10

In [40]:
a3

tensor([10,  2,  3,  4,  5])

In [45]:
x = torch.tensor([1,2,3])
# x.device
if torch.cuda.is_available():
    x = x.cuda()
x.device

device(type='cpu')

In [46]:
x = torch.ones(2,2,requires_grad = True)
y = x + 2
z = y * y * 3
out = z.mean()

In [48]:
out.backward()

In [49]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])